/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SupplierInfo = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const KPISet = IDL.Record({
  'aov' : IDL.Float64,
  'cac' : IDL.Float64,
  'revenue' : IDL.Float64,
  'roas' : IDL.Float64,
  'shippingCost' : IDL.Float64,
  'conversionRate' : IDL.Float64,
  'profit' : IDL.Float64,
  'returnRate' : IDL.Float64,
});
export const ProductPricing = IDL.Record({
  'cost' : IDL.Float64,
  'productId' : IDL.Text,
  'price' : IDL.Float64,
});
export const Product = IDL.Record({
  'sku' : IDL.Text,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'margin' : IDL.Float64,
  'price' : IDL.Float64,
});
export const BrandProfile = IDL.Record({
  'name' : IDL.Text,
  'suppliers' : IDL.Vec(SupplierInfo),
  'monthlyGoals' : KPISet,
  'pricing' : IDL.Vec(ProductPricing),
  'margin' : IDL.Float64,
  'products' : IDL.Vec(Product),
  'adBudget' : IDL.Float64,
  'weeklyGoals' : KPISet,
});
export const Time = IDL.Int;
export const Platform = IDL.Variant({
  'other' : IDL.Null,
  'meta' : IDL.Null,
  'google' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'revenue' : IDL.Float64,
  'endDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'roas' : IDL.Float64,
  'platform' : Platform,
  'spend' : IDL.Float64,
  'creativeLinks' : IDL.Vec(IDL.Text),
  'startDate' : Time,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBrand' : IDL.Func([IDL.Text, BrandProfile], [], []),
  'addCampaign' : IDL.Func([Campaign], [IDL.Nat], []),
  'addTask' : IDL.Func([Task], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBrand' : IDL.Func([IDL.Text], [], []),
  'deleteCampaign' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'generateWeeklySummary' : IDL.Func([], [IDL.Text], ['query']),
  'getBrand' : IDL.Func([IDL.Text], [IDL.Opt(BrandProfile)], ['query']),
  'getBrandsByMargin' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(BrandProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
  'getCampaignsByPlatform' : IDL.Func(
      [Platform],
      [IDL.Vec(Campaign)],
      ['query'],
    ),
  'getCampaignsSortedByROAS' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTasksByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBrand' : IDL.Func([IDL.Text, BrandProfile], [], []),
  'updateCampaign' : IDL.Func([IDL.Nat, Campaign], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SupplierInfo = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
  const KPISet = IDL.Record({
    'aov' : IDL.Float64,
    'cac' : IDL.Float64,
    'revenue' : IDL.Float64,
    'roas' : IDL.Float64,
    'shippingCost' : IDL.Float64,
    'conversionRate' : IDL.Float64,
    'profit' : IDL.Float64,
    'returnRate' : IDL.Float64,
  });
  const ProductPricing = IDL.Record({
    'cost' : IDL.Float64,
    'productId' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'margin' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const BrandProfile = IDL.Record({
    'name' : IDL.Text,
    'suppliers' : IDL.Vec(SupplierInfo),
    'monthlyGoals' : KPISet,
    'pricing' : IDL.Vec(ProductPricing),
    'margin' : IDL.Float64,
    'products' : IDL.Vec(Product),
    'adBudget' : IDL.Float64,
    'weeklyGoals' : KPISet,
  });
  const Time = IDL.Int;
  const Platform = IDL.Variant({
    'other' : IDL.Null,
    'meta' : IDL.Null,
    'google' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'revenue' : IDL.Float64,
    'endDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'roas' : IDL.Float64,
    'platform' : Platform,
    'spend' : IDL.Float64,
    'creativeLinks' : IDL.Vec(IDL.Text),
    'startDate' : Time,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBrand' : IDL.Func([IDL.Text, BrandProfile], [], []),
    'addCampaign' : IDL.Func([Campaign], [IDL.Nat], []),
    'addTask' : IDL.Func([Task], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBrand' : IDL.Func([IDL.Text], [], []),
    'deleteCampaign' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'generateWeeklySummary' : IDL.Func([], [IDL.Text], ['query']),
    'getBrand' : IDL.Func([IDL.Text], [IDL.Opt(BrandProfile)], ['query']),
    'getBrandsByMargin' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(BrandProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
    'getCampaignsByPlatform' : IDL.Func(
        [Platform],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getCampaignsSortedByROAS' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTasksByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBrands' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBrand' : IDL.Func([IDL.Text, BrandProfile], [], []),
    'updateCampaign' : IDL.Func([IDL.Nat, Campaign], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };