/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandProfile {
  'name' : string,
  'suppliers' : Array<SupplierInfo>,
  'monthlyGoals' : KPISet,
  'pricing' : Array<ProductPricing>,
  'margin' : number,
  'products' : Array<Product>,
  'adBudget' : number,
  'weeklyGoals' : KPISet,
}
export interface Campaign {
  'id' : bigint,
  'revenue' : number,
  'endDate' : [] | [Time],
  'name' : string,
  'roas' : number,
  'platform' : Platform,
  'spend' : number,
  'creativeLinks' : Array<string>,
  'startDate' : Time,
}
export interface KPISet {
  'aov' : number,
  'cac' : number,
  'revenue' : number,
  'roas' : number,
  'shippingCost' : number,
  'conversionRate' : number,
  'profit' : number,
  'returnRate' : number,
}
export type Platform = { 'other' : null } |
  { 'meta' : null } |
  { 'google' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Product {
  'sku' : string,
  'cost' : number,
  'name' : string,
  'category' : string,
  'margin' : number,
  'price' : number,
}
export interface ProductPricing {
  'cost' : number,
  'productId' : string,
  'price' : number,
}
export interface SupplierInfo { 'contact' : string, 'name' : string }
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'dueDate' : [] | [Time],
  'description' : string,
  'brand' : [] | [string],
  'priority' : Priority,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBrand' : ActorMethod<[string, BrandProfile], undefined>,
  'addCampaign' : ActorMethod<[Campaign], bigint>,
  'addTask' : ActorMethod<[Task], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBrand' : ActorMethod<[string], undefined>,
  'deleteCampaign' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'generateWeeklySummary' : ActorMethod<[], string>,
  'getBrand' : ActorMethod<[string], [] | [BrandProfile]>,
  'getBrandsByMargin' : ActorMethod<[number], Array<BrandProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[bigint], [] | [Campaign]>,
  'getCampaignsByPlatform' : ActorMethod<[Platform], Array<Campaign>>,
  'getCampaignsSortedByROAS' : ActorMethod<[], Array<Campaign>>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasksByBrand' : ActorMethod<[string], Array<Task>>,
  'getUpcomingTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBrands' : ActorMethod<[], Array<string>>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBrand' : ActorMethod<[string, BrandProfile], undefined>,
  'updateCampaign' : ActorMethod<[bigint, Campaign], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];